### PR TITLE
Label long-mode functionality

### LINKED ISSUE #131: Bug: label_set_long_mode
The method to set the wrap mode for text longer than the label doesn't seem to be recognized by the compiler, 
although it seems the LSP _does_ think it is implemented. 

Also the mode enumerations seem to be  missing : https://docs.lvgl.io/master/API/widgets/label/lv_label.html#_CPPv421_lv_label_long_mode_t

This is the actual FFI method, which works 

```
let view_summary = Label::create(&mut view).unwrap();
unsafe {lvgl_sys::lv_label_set_long_mode(view_summary.raw().unwrap().as_ptr(), 3) };
```

This is what I expected to be able to do : 

```
let view_summary = Label::create(&mut view).unwrap();
view_summary.set_long_mode(Label::LONG_SCROLL);
```

### PR DESCRIPTION
**Pull request by nia-e**
Fixes #131

### CODE REVIEW

**Comment by nia-e** [comment]
@cydergoth all good?

**Comment by cydergoth** [comment]
Looks good by eye, won't be able to test until later today (USA Central time) as I have to do my real job now 😀

**Comment by nia-e** [comment]
Alright! I'll take a look at your other issue in the meantime then

**Comment by cydergoth** [comment]
Thanks!

**Pull request merged**
