### PR TITLE
More infrastructure for `Flex` layout

### LINKED ISSUE #132: Request: Missing enumerations for layout flows
```
         style_view.set_layout(Layout::flex());
         style_view.set_flex_flow(1); // FIXME: Needs enum FLEX_FLOW_COLUMN
```

See  https://docs.lvgl.io/master/API/layouts/flex/lv_flex.html#_CPPv414lv_flex_flow_t

### PR DESCRIPTION
**Pull request by nia-e**
Closes #132

### CODE REVIEW

**Comment by nia-e** [comment]
@cydergoth let me know if there's anything else regarding this. I noticed the [`lv_style_set_flex_grow`](https://docs.rs/lvgl-sys/latest/lvgl_sys/fn.lv_style_set_flex_grow.html) fn exists also but it doesn't seem to have any preset constants so letting it just take an arbitrary `u8` should be Fine?

**Comment by cydergoth** [comment]
```
grow -- a value to set how much free space to take proportionally to other growing items.
```

From the docs, I think we're good with a u8

BTW, on the area one, I think you need to export the area mod?

**Comment by nia-e** [comment]
Gah, had missed that. Thanks! Gonna merge this now.

**Comment by cydergoth** [comment]
> Gah, had missed that. Thanks! Gonna merge this now.

No worries, I missed it too :-D

**Pull request merged**
